name: pytest
on: push
jobs:
  pytest:
    name: runner / pytest tests
    runs-on: ubuntu-latest
    env:
      USER: ${{ secrets.API_USER }}
      KEY: ${{ secrets.API_KEY }}
      URL: ${{ secrets.API_HOST }}
    strategy:
      max-parallel: 1
      matrix:
        extras:
          - .

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.10'
      - name: Install pytest
        run: |
          pip install -e ${{ matrix.extras }}
          pip install pytest pytest-cov
      - name: Run Tests
        run: |
          pytest
          coverage xml -i
      - name: Upload Coverage
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/TestResults.xml'
          check_name: 'Pytest Results'